{
 "title": "C5 Notification Server Details",
 "tags": [
  "C5",
  "Insight"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(notification_transport_message_in_total, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Notification  Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "notification_state{instance=~\"$instance\", job=~\"c5-exporter\"}"
    }
   ]
  },
  {
   "title": "Notification Overload",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(notification_overload_protection_limit_reached_total{instance=~\"$instance\"} - notification_overload_protection_limit_reached_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "notification_presence_active_subscriptions_current{instance=~\"$instance\"}",
     "legendFormat": "Active Calls"
    }
   ]
  },
  {
   "title": "Cluster Subscriptions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "notification_cluster_active_subscriptions_current{instance=~\"$instance\"}",
     "legendFormat": "Active Calls"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "stat",
   "description": "Maximum memory usage through process lifetime",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "notification_memory_used_bytes{instance=~\"$instance\"} / notification_memory_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Mem Usage"
    }
   ]
  },
  {
   "title": "Max Mem Usage",
   "type": "stat",
   "description": "Maximum memory usage through process lifetime",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "notification_memory_max_used_percent{instance=~\"$instance\"}",
     "legendFormat": "Max Mem Usage"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Version of the running software",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "notification_info{instance=~\"$instance\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Last Startup",
   "type": "stat",
   "description": "Timestamp of the last startup",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "notification_info{instance=~\"$instance\"}",
     "legendFormat": "{{ starttime }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "notification_memory_used_bytes{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "notification_memory_total_bytes{instance=\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Overload Reached",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(notification_overload_protection_limit_reached_total{instance=\"$instance\"} - notification_overload_protection_limit_reached_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Limit Reached"
    }
   ]
  },
  {
   "title": "Overload Rejects",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(notification_overload_heap_warning_rejected_in_requests_total{instance=\"$instance\"} - notification_overload_heap_warning_rejected_in_requests_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Heap Warning"
    },
    {
     "expr": "sum(notification_overload_heap_critical_rejected_in_requests_total{instance=\"$instance\"} - notification_overload_heap_critical_rejected_in_requests_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Heap Critical"
    },
    {
     "expr": "sum(notification_overload_limit1_rejected_in_requests_total{instance=\"$instance\"} - notification_overload_limit1_rejected_in_requests_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Limit1 Rejects"
    },
    {
     "expr": "sum(notification_overload_limit2_rejected_in_requests_total{instance=\"$instance\"} - notification_overload_limit2_rejected_in_requests_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Limit2 Rejects"
    },
    {
     "expr": "sum(notification_overload_limit3_rejected_in_requests_total{instance=\"$instance\"} - notification_overload_limit3_rejected_in_requests_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Limit3 Rejects"
    },
    {
     "expr": "sum(notification_overload_limit4_rejected_in_requests_total{instance=\"$instance\"} - notification_overload_limit4_rejected_in_requests_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Limit4 Rejects"
    }
   ]
  },
  { "title": "Notification Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Subscriptions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "notification_presence_active_subscriptions_current{instance=~\"$instance\"}",
     "legendFormat": "current"
    },
    {
     "expr": "notification_presence_active_subscriptions_lastmax{instance=~\"$instance\"}",
     "legendFormat": "last max "
    },
    {
     "expr": "notification_presence_active_subscriptions_lastmin{instance=~\"$instance\"}",
     "legendFormat": "last min"
    }
   ]
  },
  {
   "title": "Hazelcast In/Out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "notification_hazelcast_messages_in_total{instance=~\"$instance\"}",
     "legendFormat": "current"
    },
    {
     "expr": "notification_hazelcast_messages_out_total{instance=~\"$instance\"}",
     "legendFormat": "last max "
    },
    {
     "expr": "notification_presence_active_subscriptions_lastmin{instance=~\"$instance\"}",
     "legendFormat": "last min"
    }
   ]
  },
  {
   "title": "Subscription IP Filter",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(notification_ip_filter_denied_total{instance=\"$instance\"} - notification_ip_filter_denied_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "denied"
    },
    {
     "expr": "sum(notification_ip_filter_not_allowed_total{instance=\"$instance\"} - notification_ip_filter_not_allowed_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "not allowed"
    }
   ]
  },
  {
   "title": "Noification Queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "notification_presence_notification_queue_size_current{instance=~\"$instance\"}",
     "legendFormat": "current"
    },
    {
     "expr": "notification_presence_notification_queue_size_lastmax{instance=~\"$instance\"}",
     "legendFormat": "last max "
    },
    {
     "expr": "notification_presence_notification_queue_size_lastmin{instance=~\"$instance\"}",
     "legendFormat": "last min"
    }
   ]
  },
  {
   "title": "Request Methods",
   "type": "graph",
   "description": "Number of requests being received or sent",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(notification_request_method_invite_in_total{instance=~\"$instance\"} - notification_request_method_invite_in_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "INVITE IN"
    },
    {
     "expr": "sum(notification_request_method_subscribe_in_total{instance=~\"$instance\"} - notification_request_method_subscribe_in_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "SUBSCRIBE IN"
    },
    {
     "expr": "sum(notification_request_method_notify_out_total{instance=~\"$instance\"} - notification_request_method_notify_out_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "NOTIFY OUT"
    },
    {
     "expr": "sum(notification_request_method_register_in_total{instance=~\"$instance\"} - notification_request_method_register_in_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "REGISTER IN"
    }
   ]
  },
  { "title": "Internal Communication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "WebSocket Connections",
   "type": "graph",
   "description": "Number of active websocket connections",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "notification_ws_connections_current",
     "legendFormat": "active"
    },
    {
     "expr": "notification_ws_connections_lastmin{instance=~\"$instance\"} ",
     "legendFormat": "last min"
    },
    {
     "expr": "notification_ws_connections_lastmax{instance=~\"$instance\"} ",
     "legendFormat": "last max"
    }
   ]
  },
  {
   "title": "Hazelcast topics",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(notification_ws_agent_ev_in_total{instance=~\"$instance\"} - notification_ws_agent_ev_in_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Agent in"
    },
    {
     "expr": "sum(notification_ws_agent_ev_out_total{instance=~\"$instance\"} - notification_ws_agent_ev_out_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Agent out"
    },
    {
     "expr": "sum(notification_ws_call_ev_total{instance=~\"$instance\"} - notification_ws_call_ev_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Calls"
    },
    {
     "expr": "sum(notification_ws_call_notify_in_total{instance=~\"$instance\"} - notification_ws_call_notify_in_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Call notify in"
    },
    {
     "expr": "sum(notification_ws_call_notify_out_total{instance=~\"$instance\"} - notification_ws_call_notify_out_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Call notify out"
    },
    {
     "expr": "sum(notification_ws_call_sync_in_total{instance=~\"$instance\"} - notification_ws_call_sync_in_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Call sync in"
    },
    {
     "expr": "sum(notification_ws_call_sync_out_total{instance=~\"$instance\"} - notification_ws_call_sync_out_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Call sync out"
    }
   ]
  },
  {
   "title": "C5 Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(process_cpu_seconds_system_total{instance=~\"$instance\",job=\"c5-exporter\"} - process_cpu_seconds_system_total{instance=~\"$instance\",job=\"c5-exporter\"} offset $__interval >= 0) by (detector)",
       "legendFormat": "system"
      },
      {
       "expr": "sum(process_cpu_seconds_user_total{instance=~\"$instance\",job=\"c5-exporter\"} - process_cpu_seconds_user_total{instance=~\"$instance\",job=\"c5-exporter\"} offset $__interval >= 0) by (detector)",
       "legendFormat": "user"
      }
     ]
    },
    {
     "title": "Go Process Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "Resident"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{instance=~\"$instance\"}",
       "legendFormat": "Heap used"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance\"}",
       "legendFormat": "Stack used"
      }
     ]
    },
    {
     "title": "Go Internals",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{instance=~\"$instance\"}",
       "legendFormat": "Open files"
      },
      {
       "expr": "go_goroutines{instance=~\"$instance\"}",
       "legendFormat": "Go Routines"
      },
      {
       "expr": "go_threads{instance=~\"$instance\"}",
       "legendFormat": "Go Threads"
      }
     ]
    }
   ]
  }
 ]
}