{
 "title": "C5 Business Trunk Details",
 "tags": [ "C5" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(sipproxyd_transport_message_in_total, instance)"
    }
   },
   {
    "name": "name",
    "query": {
     "query": "label_values(sipproxyd_bt_active_calls_trunk_current, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Proxy Status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(sipproxyd_state{instance=~\"$instance\", job=~\"c5-exporter\"})"
      }
     ]
    },
    {
     "title": "Proxy Overload",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sipproxyd_overload_protection_limit_reached_total{instance=~\"$instance\"} - sipproxyd_overload_protection_limit_reached_total{instance=~\"$instance\"} offset $__interval >= 0)"
      }
     ]
    },
    {
     "title": "TU Queue State",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "min(sipproxyd_tu_queue_state{instance=~\"$instance\",job=~\"c5-exporter\"})"
      }
     ]
    },
    {
     "title": "Active Calls",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(sipproxyd_call_control_active_calls_current{instance=~\"$instance\"})",
       "legendFormat": "Active Calls"
      }
     ]
    },
    {
     "title": "Mem Usage",
     "type": "singlestat",
     "description": "Maximum memory usage through process lifetime",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(sipproxyd_memory_used_bytes{instance=~\"$instance\"} / sipproxyd_memory_total_bytes{instance=~\"$instance\"})",
       "legendFormat": "Mem Usage"
      }
     ]
    },
    {
     "title": "Max Mem Usage",
     "type": "singlestat",
     "description": "Maximum memory usage through process lifetime",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(sipproxyd_memory_max_used_percent{instance=~\"$instance\"})",
       "legendFormat": "Max Mem Usage"
      }
     ]
    },
    {
     "title": "Version",
     "type": "singlestat",
     "description": "Version of the running software",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "expr": "max(sipproxyd_info{instance=~\"$instance\"}) without (starttime)",
       "legendFormat": "{{ version }}"
      }
     ]
    },
    {
     "title": "Last Startup",
     "type": "singlestat",
     "description": "Timestamp of the last startup",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "expr": "topk(1, count(sipproxyd_info{instance=~\"$instance\"}) by (starttime))",
       "legendFormat": "{{ starttime }}"
      }
     ]
    }
   ]
  },
  { "title": "Trunk $name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "name" },
  {
   "title": "Active Calls",
   "type": "graph",
   "description": "Number of active business trunk calls",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_bt_active_calls_trunk_current{instance=~\"$instance\",name=~\"$name\"})",
     "legendFormat": "active"
    },
    {
     "expr": "sum(sipproxyd_bt_active_calls_trunk_lastmin{instance=~\"$instance\",name=~\"$name\"})",
     "legendFormat": "last min"
    },
    {
     "expr": "sum(sipproxyd_bt_active_calls_trunk_lastmax{instance=~\"$instance\",name=~\"$name\"})",
     "legendFormat": "last max"
    }
   ]
  },
  {
   "title": "Limit Reached",
   "type": "graph",
   "description": "Number of active business trunk calls",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_bt_calls_limit_reached_trunk_total{instance=~\"$instance\",name=~\"$name\"})",
     "legendFormat": "limit"
    }
   ]
  },
  { "title": "Trunk $name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Active Calls",
   "type": "graph",
   "description": "Number of active business trunk calls",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_bt_active_calls_trunk_current{instance=~\"$instance\",name=~\"$name\"})",
     "legendFormat": "active"
    },
    {
     "expr": "sum(sipproxyd_bt_active_calls_trunk_lastmin{instance=~\"$instance\",name=~\"$name\"})",
     "legendFormat": "last min"
    },
    {
     "expr": "sum(sipproxyd_bt_active_calls_trunk_lastmax{instance=~\"$instance\",name=~\"$name\"})",
     "legendFormat": "last max"
    }
   ]
  },
  {
   "title": "Limit Reached",
   "type": "graph",
   "description": "Number of active business trunk calls",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_bt_calls_limit_reached_trunk_total{instance=~\"$instance\",name=~\"$name\"})",
     "legendFormat": "limit"
    }
   ]
  },
  { "title": "Trunk $name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Active Calls",
   "type": "graph",
   "description": "Number of active business trunk calls",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_bt_active_calls_trunk_current{instance=~\"$instance\",name=~\"$name\"})",
     "legendFormat": "active"
    },
    {
     "expr": "sum(sipproxyd_bt_active_calls_trunk_lastmin{instance=~\"$instance\",name=~\"$name\"})",
     "legendFormat": "last min"
    },
    {
     "expr": "sum(sipproxyd_bt_active_calls_trunk_lastmax{instance=~\"$instance\",name=~\"$name\"})",
     "legendFormat": "last max"
    }
   ]
  },
  {
   "title": "Limit Reached",
   "type": "graph",
   "description": "Number of active business trunk calls",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_bt_calls_limit_reached_trunk_total{instance=~\"$instance\",name=~\"$name\"})",
     "legendFormat": "limit"
    }
   ]
  },
  { "title": "Trunk $name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Active Calls",
   "type": "graph",
   "description": "Number of active business trunk calls",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_bt_active_calls_trunk_current{instance=~\"$instance\",name=~\"$name\"})",
     "legendFormat": "active"
    },
    {
     "expr": "sum(sipproxyd_bt_active_calls_trunk_lastmin{instance=~\"$instance\",name=~\"$name\"})",
     "legendFormat": "last min"
    },
    {
     "expr": "sum(sipproxyd_bt_active_calls_trunk_lastmax{instance=~\"$instance\",name=~\"$name\"})",
     "legendFormat": "last max"
    }
   ]
  },
  {
   "title": "Limit Reached",
   "type": "graph",
   "description": "Number of active business trunk calls",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_bt_calls_limit_reached_trunk_total{instance=~\"$instance\",name=~\"$name\"})",
     "legendFormat": "limit"
    }
   ]
  },
  { "title": "Trunk $name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Active Calls",
   "type": "graph",
   "description": "Number of active business trunk calls",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_bt_active_calls_trunk_current{instance=~\"$instance\",name=~\"$name\"})",
     "legendFormat": "active"
    },
    {
     "expr": "sum(sipproxyd_bt_active_calls_trunk_lastmin{instance=~\"$instance\",name=~\"$name\"})",
     "legendFormat": "last min"
    },
    {
     "expr": "sum(sipproxyd_bt_active_calls_trunk_lastmax{instance=~\"$instance\",name=~\"$name\"})",
     "legendFormat": "last max"
    }
   ]
  },
  {
   "title": "Limit Reached",
   "type": "graph",
   "description": "Number of active business trunk calls",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_bt_calls_limit_reached_trunk_total{instance=~\"$instance\",name=~\"$name\"})",
     "legendFormat": "limit"
    }
   ]
  }
 ]
}