{
 "title": "XMS Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "XMS Instance",
    "query": {
     "query": "label_values(resourcelicenses_basic_audio_used, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$instance", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Resource Counters",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resourcecounters_received_sip_responses{instance=~\"$instance\"}",
     "legendFormat": "Received SIP Responses "
    },
    {
     "expr": "resourcecounters_sent_sip_invites{instance=~\"$instance\"}",
     "legendFormat": "Sent SIP Invites"
    },
    {
     "expr": "resourcecounters_sent_sip_responses{instance=~\"$instance\"}",
     "legendFormat": "Sent SIP Responses "
    }
   ]
  },
  {
   "title": "Licenses - Basic Audio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resourcelicenses_basic_audio_used{instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "resourcelicenses_basic_audio_free{instance=~\"$instance\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Licenses - LBR Audio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resourcelicenses_lbr_audio_used{instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "resourcelicenses_lbr_audio_free{instance=~\"$instance\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Licenses - GSMAMR Audio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resourcelicenses_gsmamr_audio_used{instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "resourcelicenses_gsmamr_audio_free{instance=~\"$instance\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Licenses - HD Voice",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resourcelicenses_hd_voice_used{instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "resourcelicenses_hd_voice_free{instance=~\"$instance\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Licenses - IPCC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resourcelicenses_ipcc_used{instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "resourcelicenses_ipcc_free{instance=~\"$instance\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Licenses - Advanced Video",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resourcelicenses_advanced_video_used{instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "resourcelicenses_advanced_video_free{instance=~\"$instance\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Licenses - High-res Video",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resourcelicenses_high_res_video_used{instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "resourcelicenses_high_res_video_free{instance=~\"$instance\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Licenses - MRCP Speech Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resourcelicenses_mrcp_speech_server_used{instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "resourcelicenses_mrcp_speech_server_free{instance=~\"$instance\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Licenses - MSRP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resourcelicenses_msrp_used{instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "resourcelicenses_msrp_free{instance=~\"$instance\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Licenses - Fax",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resourcelicenses_fax_used{instance=~\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "resourcelicenses_fax_free{instance=~\"$instance\"}",
     "legendFormat": "Free"
    }
   ]
  }
 ]
}