{
 "title": "C5 CSTAGW Details",
 "tags": [
  "C5",
  "Insight"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(cstagwd_transport_message_in_total, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CSTAGW  Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cstagwd_state{instance=~\"$instance\", job=~\"c5-exporter\"}"
    }
   ]
  },
  {
   "title": "CSTAGW Overload",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cstagwd_overload_protection_limit_reached_total{instance=~\"$instance\"} - cstagwd_overload_protection_limit_reached_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)"
    }
   ]
  },
  {
   "title": "TU Queue ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cstagwd_tu_queue_state{instance=~\"$instance\", job=~\"c5-exporter\"}"
    }
   ]
  },
  {
   "title": "Active CSTA Sessions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cstagwd_transaction_and_tu_active_ua_sessions_current{instance=~\"$instance\"}",
     "legendFormat": "Active Sessions"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "stat",
   "description": "Maximum memory usage through process lifetime",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cstagwd_memory_used_bytes{instance=~\"$instance\"} / cstagwd_memory_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Mem Usage"
    }
   ]
  },
  {
   "title": "Max Mem Usage",
   "type": "stat",
   "description": "Maximum memory usage through process lifetime",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cstagwd_memory_max_used_percent{instance=~\"$instance\"}",
     "legendFormat": "Max Mem Usage"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Version of the running software",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cstagwd_info{instance=~\"$instance\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Last Startup",
   "type": "stat",
   "description": "Timestamp of the last startup",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cstagwd_info{instance=~\"$instance\"}",
     "legendFormat": "{{ starttime }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cstagwd_memory_used_bytes{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "cstagwd_memory_total_bytes{instance=\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Overload Reached",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(cstagwd_overload_protection_limit_reached_total{instance=\"$instance\"} - cstagwd_overload_protection_limit_reached_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Limit Reached"
    }
   ]
  },
  {
   "title": "Overload Rejects",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(cstagwd_overload_heap_warning_rejected_in_requests_total{instance=\"$instance\"} - cstagwd_overload_heap_warning_rejected_in_requests_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Heap Warning"
    },
    {
     "expr": "sum(cstagwd_overload_heap_critical_rejected_in_requests_total{instance=\"$instance\"} - cstagwd_overload_heap_critical_rejected_in_requests_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Heap Critical"
    },
    {
     "expr": "sum(cstagwd_overload_limit1_rejected_in_requests_total{instance=\"$instance\"} - cstagwd_overload_limit1_rejected_in_requests_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Limit1 Rejects"
    },
    {
     "expr": "sum(cstagwd_overload_limit2_rejected_in_requests_total{instance=\"$instance\"} - cstagwd_overload_limit2_rejected_in_requests_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Limit2 Rejects"
    },
    {
     "expr": "sum(cstagwd_overload_limit3_rejected_in_requests_total{instance=\"$instance\"} - cstagwd_overload_limit3_rejected_in_requests_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Limit3 Rejects"
    },
    {
     "expr": "sum(cstagwd_overload_limit4_rejected_in_requests_total{instance=\"$instance\"} - cstagwd_overload_limit4_rejected_in_requests_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Limit4 Rejects"
    }
   ]
  },
  { "title": "CSTAGW Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CSTAGW IP Filter",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(cstagwd_ip_filter_denied_total{instance=\"$instance\"} - cstagwd_ip_filter_denied_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "denied"
    },
    {
     "expr": "sum(cstagwd_ip_filter_not_allowed_total{instance=\"$instance\"} - cstagwd_ip_filter_not_allowed_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "not allowed"
    }
   ]
  },
  {
   "title": "TU  Queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cstagwd_transaction_and_tu_tu_manager_queue_size_current{instance=~\"$instance\"}",
     "legendFormat": "current"
    },
    {
     "expr": "cstagwd_transaction_and_tu_tu_manager_queue_size_lastmax{instance=~\"$instance\"}",
     "legendFormat": "last max "
    },
    {
     "expr": "cstagwd_transaction_and_tu_tu_manager_queue_size_lastmin{instance=~\"$instance\"}",
     "legendFormat": "last min"
    }
   ]
  },
  {
   "title": "Request Methods",
   "type": "graph",
   "description": "Number of requests being received or sent",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cstagwd_request_method_invite_in_total{instance=~\"$instance\"} - cstagwd_request_method_invite_in_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "INVITE IN"
    },
    {
     "expr": "sum(cstagwd_request_method_info_in_total{instance=~\"$instance\"} - cstagwd_request_method_info_in_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "INFO IN"
    }
   ]
  },
  {
   "title": "C5 Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(process_cpu_seconds_system_total{instance=~\"$instance\",job=\"c5-exporter\"} - process_cpu_seconds_system_total{instance=~\"$instance\",job=\"c5-exporter\"} offset $__interval >= 0) by (detector)",
       "legendFormat": "system"
      },
      {
       "expr": "sum(process_cpu_seconds_user_total{instance=~\"$instance\",job=\"c5-exporter\"} - process_cpu_seconds_user_total{instance=~\"$instance\",job=\"c5-exporter\"} offset $__interval >= 0) by (detector)",
       "legendFormat": "user"
      }
     ]
    },
    {
     "title": "Go Process Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "Resident"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{instance=~\"$instance\"}",
       "legendFormat": "Heap used"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance\"}",
       "legendFormat": "Stack used"
      }
     ]
    },
    {
     "title": "Go Internals",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{instance=~\"$instance\"}",
       "legendFormat": "Open files"
      },
      {
       "expr": "go_goroutines{instance=~\"$instance\"}",
       "legendFormat": "Go Routines"
      },
      {
       "expr": "go_threads{instance=~\"$instance\"}",
       "legendFormat": "Go Threads"
      }
     ]
    }
   ]
  }
 ]
}