{
 "title": "C5 Business Trunk Overview",
 "tags": [
  "C5",
  "Overview"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(sipproxyd_transport_message_in_total, instance)"
    }
   },
   {
    "name": "name",
    "query": {
     "query": "label_values(sipproxyd_bt_active_calls_trunk_current, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Proxy Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sipproxyd_state{instance=~\"$instance\", job=~\"c5-exporter\"})"
    }
   ]
  },
  {
   "title": "Proxy Overload",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sipproxyd_overload_protection_limit_reached_total{instance=~\"$instance\"} - sipproxyd_overload_protection_limit_reached_total{instance=~\"$instance\"} offset $__interval >= 0)"
    }
   ]
  },
  {
   "title": "TU Queue State",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(sipproxyd_tu_queue_state{instance=~\"$instance\",job=~\"c5-exporter\"})"
    }
   ]
  },
  {
   "title": "Active Calls",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sipproxyd_call_control_active_calls_current{instance=~\"$instance\"})",
     "legendFormat": "Active Calls"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "singlestat",
   "description": "Maximum memory usage through process lifetime",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sipproxyd_memory_used_bytes{instance=~\"$instance\"} / sipproxyd_memory_total_bytes{instance=~\"$instance\"})",
     "legendFormat": "Mem Usage"
    }
   ]
  },
  {
   "title": "Max Mem Usage",
   "type": "singlestat",
   "description": "Maximum memory usage through process lifetime",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sipproxyd_memory_max_used_percent{instance=~\"$instance\"})",
     "legendFormat": "Max Mem Usage"
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "description": "Version of the running software",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "max(sipproxyd_info{instance=~\"$instance\"}) without (starttime)",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Last Startup",
   "type": "singlestat",
   "description": "Timestamp of the last startup",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, count(sipproxyd_info{instance=~\"$instance\"}) by (starttime))",
     "legendFormat": "{{ starttime }}"
    }
   ]
  },
  {
   "title": "Concurrent Calls",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(acdqueued_call_control_active_calls_current{instance=~\"$instance\"})",
     "legendFormat": "current"
    },
    {
     "expr": "sum(acdqueued_call_control_active_calls_lastmax{instance=~\"$instance\"})",
     "legendFormat": "last max "
    },
    {
     "expr": "sum(acdqueued_call_control_active_calls_lastmin{instance=~\"$instance\"})",
     "legendFormat": "last min"
    }
   ]
  },
  {
   "title": "Call Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(acdqueued_call_control_orig_authentication_required_total{instance=~\"$instance\"} - acdqueued_call_control_orig_authentication_required_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Auth required"
    },
    {
     "expr": "sum(acdqueued_call_control_orig_client_error_total{instance=~\"$instance\"} - acdqueued_call_control_orig_client_error_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Client error"
    },
    {
     "expr": "sum(acdqueued_call_control_orig_server_error_total{instance=~\"$instance\"} - acdqueued_call_control_orig_server_error_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Server error"
    },
    {
     "expr": "sum(acdqueued_call_control_orig_global_error_total{instance=~\"$instance\"} - acdqueued_call_control_orig_global_error_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Global error"
    }
   ]
  },
  {
   "title": "Overload Reached",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(acdqueued_overload_protection_limit_reached_total{instance=~\"$instance\"} - acdqueued_overload_protection_limit_reached_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Limit Reached"
    }
   ]
  },
  {
   "title": "Overload Rejects",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(acdqueued_overload_heap_warning_rejected_in_requests_total{instance=~\"$instance\"} - acdqueued_overload_heap_warning_rejected_in_requests_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Heap Warning"
    },
    {
     "expr": "sum(acdqueued_overload_heap_critical_rejected_in_requests_total{instance=~\"$instance\"} - acdqueued_overload_heap_critical_rejected_in_requests_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Heap Critical"
    },
    {
     "expr": "sum(acdqueued_overload_limit1_rejected_in_requests_total{instance=~\"$instance\"} - acdqueued_overload_limit1_rejected_in_requests_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Limit1 Rejects"
    },
    {
     "expr": "sum(acdqueued_overload_limit2_rejected_in_requests_total{instance=~\"$instance\"} - acdqueued_overload_limit2_rejected_in_requests_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Limit2 Rejects"
    },
    {
     "expr": "sum(acdqueued_overload_limit3_rejected_in_requests_total{instance=~\"$instance\"} - acdqueued_overload_limit3_rejected_in_requests_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Limit3 Rejects"
    },
    {
     "expr": "sum(acdqueued_overload_limit4_rejected_in_requests_total{instance=~\"$instance\"} - acdqueued_overload_limit4_rejected_in_requests_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Limit4 Rejects"
    }
   ]
  },
  { "title": "Business Trunk Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Active Calls",
   "type": "graph",
   "description": "Number of active business trunk calls",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sipproxyd_bt_active_calls_trunk_current{instance=~\"$instance\",name=~\"$name\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Limit Reached",
   "type": "graph",
   "description": "Number of active business trunk calls",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sipproxyd_bt_calls_limit_reached_trunk_total{instance=~\"$instance\",name=~\"$name\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Maximum Calls (Last)",
   "type": "graph",
   "description": "Number of maximum calls in the last period of abusiness trunk",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sipproxyd_bt_active_calls_trunk_lastmin{instance=~\"$instance\",name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "C5 Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(process_cpu_seconds_system_total{instance=~\"$instance\",job=\"c5-exporter\"} - process_cpu_seconds_system_total{instance=~\"$instance\",job=\"c5-exporter\"} offset $__interval >= 0) by (detector)",
       "legendFormat": "system"
      },
      {
       "expr": "sum(process_cpu_seconds_user_total{instance=~\"$instance\",job=\"c5-exporter\"} - process_cpu_seconds_user_total{instance=~\"$instance\",job=\"c5-exporter\"} offset $__interval >= 0) by (detector)",
       "legendFormat": "user"
      }
     ]
    },
    {
     "title": "Go Process Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "Resident"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{instance=~\"$instance\"}",
       "legendFormat": "Heap used"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance\"}",
       "legendFormat": "Stack used"
      }
     ]
    },
    {
     "title": "Go Internals",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{instance=~\"$instance\"}",
       "legendFormat": "Open files"
      },
      {
       "expr": "go_goroutines{instance=~\"$instance\"}",
       "legendFormat": "Go Routines"
      },
      {
       "expr": "go_threads{instance=~\"$instance\"}",
       "legendFormat": "Go Threads"
      }
     ]
    }
   ]
  }
 ]
}