{
 "title": "TELES C5 ACD",
 "tags": [ "C5" ],
 "time": { "from": "2020-02-19T13:59:37.670Z", "to": "2020-02-19T14:06:23.166Z" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(acdqueued_transport_message_in_total, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ACD Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(acdqueued_state{instance=~\"$instance\", job=~\"c5-exporter\"})"
    }
   ]
  },
  {
   "title": "ACD Overload",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(acdqueued_overload_protection_limit_reached_total{instance=~\"$instance\"} - acdqueued_overload_protection_limit_reached_total{instance=~\"$instance\"} offset $__interval >= 0)"
    }
   ]
  },
  {
   "title": "TU Queue State",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(acdqueued_tu_queue_state{instance=~\"$instance\",job=~\"c5-exporter\"})"
    }
   ]
  },
  {
   "title": "Active Calls",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(acdqueued_call_control_active_calls_current{instance=~\"$instance\"})",
     "legendFormat": "Active Calls"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "singlestat",
   "description": "Maximum memory usage through process lifetime",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(acdqueued_memory_used_bytes{instance=~\"$instance\"} / acdqueued_memory_total_bytes{instance=~\"$instance\"})",
     "legendFormat": "Mem Usage"
    }
   ]
  },
  {
   "title": "Max Mem Usage",
   "type": "singlestat",
   "description": "Maximum memory usage through process lifetime",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(acdqueued_memory_max_used_percent{instance=~\"$instance\"})",
     "legendFormat": "Max Mem Usage"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(acdqueued_memory_used_bytes{instance=~\"$instance\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(acdqueued_memory_total_bytes{instance=~\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Overload Reached",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(acdqueued_overload_protection_limit_reached_total{instance=~\"$instance\"} - acdqueued_overload_protection_limit_reached_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Limit Reached"
    }
   ]
  },
  {
   "title": "Overload Rejects",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(acdqueued_overload_heap_warning_rejected_in_requests_total{instance=~\"$instance\"} - acdqueued_overload_heap_warning_rejected_in_requests_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Heap Warning"
    },
    {
     "expr": "sum(acdqueued_overload_heap_critical_rejected_in_requests_total{instance=~\"$instance\"} - acdqueued_overload_heap_critical_rejected_in_requests_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Heap Critical"
    },
    {
     "expr": "sum(acdqueued_overload_limit1_rejected_in_requests_total{instance=~\"$instance\"} - acdqueued_overload_limit1_rejected_in_requests_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Limit1 Rejects"
    },
    {
     "expr": "sum(acdqueued_overload_limit2_rejected_in_requests_total{instance=~\"$instance\"} - acdqueued_overload_limit2_rejected_in_requests_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Limit2 Rejects"
    },
    {
     "expr": "sum(acdqueued_overload_limit3_rejected_in_requests_total{instance=~\"$instance\"} - acdqueued_overload_limit3_rejected_in_requests_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Limit3 Rejects"
    },
    {
     "expr": "sum(acdqueued_overload_limit4_rejected_in_requests_total{instance=~\"$instance\"} - acdqueued_overload_limit4_rejected_in_requests_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Limit4 Rejects"
    }
   ]
  },
  { "title": "Call Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Concurrent Calls",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(acdqueued_call_control_active_calls_current{instance=~\"$instance\"})",
     "legendFormat": "current"
    },
    {
     "expr": "sum(acdqueued_call_control_active_calls_lastmax{instance=~\"$instance\"})",
     "legendFormat": "last max "
    },
    {
     "expr": "sum(acdqueued_call_control_active_calls_lastmin{instance=~\"$instance\"})",
     "legendFormat": "last min"
    }
   ]
  },
  {
   "title": "Call Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(acdqueued_call_control_orig_authentication_required_total{instance=~\"$instance\"} - acdqueued_call_control_orig_authentication_required_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Auth required"
    },
    {
     "expr": "sum(acdqueued_call_control_orig_client_error_total{instance=~\"$instance\"} - acdqueued_call_control_orig_client_error_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Client error"
    },
    {
     "expr": "sum(acdqueued_call_control_orig_server_error_total{instance=~\"$instance\"} - acdqueued_call_control_orig_server_error_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Server error"
    },
    {
     "expr": "sum(acdqueued_call_control_orig_global_error_total{instance=~\"$instance\"} - acdqueued_call_control_orig_global_error_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Global error"
    }
   ]
  },
  {
   "title": "Call Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(acdqueued_call_control_orig_call_connected_total{instance=~\"$instance\"} - acdqueued_call_control_orig_call_connected_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Connected"
    },
    {
     "expr": "sum(acdqueued_call_control_orig_call_fast_connected_total{instance=~\"$instance\"} - acdqueued_call_control_orig_call_fast_connected_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Fast connected"
    },
    {
     "expr": "sum(acdqueued_call_control_orig_call_setup_success_total{instance=\"$instance\"} - acdqueued_call_control_orig_call_setup_success_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Setup success"
    },
    {
     "expr": "sum(acdqueued_call_control_orig_redirection_total{instance=~\"$instance\"} - acdqueued_call_control_orig_redirection_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Redirected"
    }
   ]
  },
  { "title": "Internal Communication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "WebSocket Connections",
   "type": "graph",
   "description": "Number of active websocket connections",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(acdqueued_ws_connections_current{instance=~\"$instance\"})",
     "legendFormat": "active"
    },
    {
     "expr": "sum(acdqueued_ws_connections_lastmin{instance=~\"$instance\"})",
     "legendFormat": "last min"
    },
    {
     "expr": "sum(acdqueued_ws_connections_lastmax{instance=~\"$instance\"})",
     "legendFormat": "last max"
    }
   ]
  },
  {
   "title": "RCC Connections",
   "type": "graph",
   "description": "Number of active websocket connections",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(acdqueued_general_rcc_active_connections_current{instance=~\"$instance\"})",
     "legendFormat": "active"
    },
    {
     "expr": "sum(acdqueued_general_rcc_active_connections_lastmin{instance=~\"$instance\"})",
     "legendFormat": "last min"
    },
    {
     "expr": "sum(acdqueued_general_rcc_active_connections_lastmax{instance=~\"$instance\"})",
     "legendFormat": "last max"
    }
   ]
  },
  {
   "title": "WebSocket Messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(acdqueued_ws_agent_ev_in_total{instance=~\"$instance\"} - acdqueued_ws_agent_ev_in_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Agent in"
    },
    {
     "expr": "sum(acdqueued_ws_agent_ev_out_total{instance=~\"$instance\"} - acdqueued_ws_agent_ev_out_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Agent out"
    },
    {
     "expr": "sum(acdqueued_ws_call_ev_total{instance=~\"$instance\"} - acdqueued_ws_call_ev_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Calls"
    },
    {
     "expr": "sum(acdqueued_ws_call_notify_in_total{instance=~\"$instance\"} - acdqueued_ws_call_notify_in_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Call notify in"
    },
    {
     "expr": "sum(acdqueued_ws_call_notify_out_total{instance=~\"$instance\"} - acdqueued_ws_call_notify_out_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Call notify out"
    },
    {
     "expr": "sum(acdqueued_ws_call_sync_in_total{instance=~\"$instance\"} - acdqueued_ws_call_sync_in_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Call sync in"
    },
    {
     "expr": "sum(acdqueued_ws_call_sync_out_total{instance=~\"$instance\"} - acdqueued_ws_call_sync_out_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Call sync out"
    }
   ]
  },
  {
   "title": "RCC Messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(acdqueued_general_rcc_in_commands_total{instance=~\"$instance\"} - acdqueued_general_rcc_in_commands_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Commands in"
    },
    {
     "expr": "sum(acdqueued_general_rcc_out_commands_total{instance=~\"$instance\"} - acdqueued_general_rcc_out_commands_total{instance=~\"$instance\"} offset $__interval >= 0)",
     "legendFormat": "Commands out"
    }
   ]
  },
  {
   "title": "C5 Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(process_cpu_seconds_system_total{instance=~\"$instance\",job=\"c5-exporter\"} - process_cpu_seconds_system_total{instance=~\"$instance\",job=\"c5-exporter\"} offset $__interval >= 0) by (detector)",
       "legendFormat": "system"
      },
      {
       "expr": "sum(process_cpu_seconds_user_total{instance=~\"$instance\",job=\"c5-exporter\"} - process_cpu_seconds_user_total{instance=~\"$instance\",job=\"c5-exporter\"} offset $__interval >= 0) by (detector)",
       "legendFormat": "user"
      }
     ]
    },
    {
     "title": "Go Process Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "Resident"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{instance=~\"$instance\"}",
       "legendFormat": "Heap used"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance\"}",
       "legendFormat": "Stack used"
      }
     ]
    },
    {
     "title": "Go Internals",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{instance=~\"$instance\"}",
       "legendFormat": "Open files"
      },
      {
       "expr": "go_goroutines{instance=~\"$instance\"}",
       "legendFormat": "Go Routines"
      },
      {
       "expr": "go_threads{instance=~\"$instance\"}",
       "legendFormat": "Go Threads"
      }
     ]
    }
   ]
  }
 ]
}