{
 "title": "C5 Proxy Details",
 "tags": [
  "C5",
  "Insight"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(sipproxyd_transport_message_in_total, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Proxy Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sipproxyd_state{instance=~\"$instance\", job=~\"c5-exporter\"}"
    }
   ]
  },
  {
   "title": "Proxy Overload",
   "type": "singlestat",
   "description": "Show any proxy overload situations within the last 30 minutes",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sipproxyd_overload_protection_limit_reached_total{instance=~\"$instance\"} - sipproxyd_overload_protection_limit_reached_total{instance=~\"$instance\"} offset 30m >= 0) by (instance)"
    }
   ]
  },
  {
   "title": "TU Queue State",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sipproxyd_tu_queue_state{instance=~\"$instance\",job=~\"c5-exporter\"}"
    }
   ]
  },
  {
   "title": "Active Calls",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sipproxyd_call_control_active_calls_current{instance=~\"$instance\"}",
     "legendFormat": "Active Calls"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "singlestat",
   "description": "Maximum memory usage through process lifetime",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sipproxyd_memory_used_bytes{instance=~\"$instance\"} / sipproxyd_memory_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Mem Usage"
    }
   ]
  },
  {
   "title": "Max Mem Usage",
   "type": "singlestat",
   "description": "Maximum memory usage through process lifetime",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sipproxyd_memory_max_used_percent{instance=~\"$instance\"}",
     "legendFormat": "Max Mem Usage"
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "description": "Version of the running software",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, sipproxyd_info{instance=~\"$instance\"}) by (version)",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Last Startup",
   "type": "singlestat",
   "description": "Timestamp of the last startup",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1, sipproxyd_info{instance=~\"$instance\"})",
     "legendFormat": "{{ starttime }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sipproxyd_memory_used_bytes{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "sipproxyd_memory_total_bytes{instance=\"$instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Overload Reached",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_overload_protection_limit_reached_total{instance=\"$instance\"} - sipproxyd_overload_protection_limit_reached_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Limit Reached"
    }
   ]
  },
  {
   "title": "Overload Rejects",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_overload_heap_warning_rejected_in_requests_total{instance=\"$instance\"} - sipproxyd_overload_heap_warning_rejected_in_requests_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Heap Warning"
    },
    {
     "expr": "sum(sipproxyd_overload_heap_critical_rejected_in_requests_total{instance=\"$instance\"} - sipproxyd_overload_heap_critical_rejected_in_requests_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Heap Critical"
    },
    {
     "expr": "sum(sipproxyd_overload_limit1_rejected_in_requests_total{instance=\"$instance\"} - sipproxyd_overload_limit1_rejected_in_requests_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Limit1 Rejects"
    },
    {
     "expr": "sum(sipproxyd_overload_limit2_rejected_in_requests_total{instance=\"$instance\"} - sipproxyd_overload_limit2_rejected_in_requests_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Limit2 Rejects"
    },
    {
     "expr": "sum(sipproxyd_overload_limit3_rejected_in_requests_total{instance=\"$instance\"} - sipproxyd_overload_limit3_rejected_in_requests_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Limit3 Rejects"
    },
    {
     "expr": "sum(sipproxyd_overload_limit4_rejected_in_requests_total{instance=\"$instance\"} - sipproxyd_overload_limit4_rejected_in_requests_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Limit4 Rejects"
    }
   ]
  },
  { "title": "Call Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Concurrent Calls",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sipproxyd_call_control_active_calls_current{instance=~\"$instance\"}",
     "legendFormat": "current"
    },
    {
     "expr": "sipproxyd_call_control_active_calls_lastmax{instance=~\"$instance\"}",
     "legendFormat": "last max "
    },
    {
     "expr": "sipproxyd_call_control_active_calls_lastmin{instance=~\"$instance\"}",
     "legendFormat": "last min"
    }
   ]
  },
  {
   "title": "Business Trunk Calls",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sipproxyd_bt_active_calls_current{instance=~\"$instance\"}",
     "legendFormat": "current"
    },
    {
     "expr": "sipproxyd_bt_active_calls_lastmax{instance=~\"$instance\"}",
     "legendFormat": "last max "
    },
    {
     "expr": "sipproxyd_bt_active_calls_lastmin{instance=~\"$instance\"}",
     "legendFormat": "last min"
    },
    {
     "expr": "sipproxyd_bt_active_calls_lastavg{instance=~\"$instance\"}",
     "legendFormat": "last avg"
    }
   ]
  },
  {
   "title": "Call Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_call_control_orig_call_connected_total{instance=\"$instance\"} - sipproxyd_call_control_orig_call_connected_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Connected"
    },
    {
     "expr": "sum(sipproxyd_call_control_orig_call_fast_connected_total{instance=\"$instance\"} - sipproxyd_call_control_orig_call_fast_connected_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Fast connected"
    },
    {
     "expr": "sum(sipproxyd_call_control_orig_call_setup_success_total{instance=\"$instance\"} - sipproxyd_call_control_orig_call_setup_success_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Setup success"
    },
    {
     "expr": "sum(sipproxyd_call_control_orig_redirection_total{instance=\"$instance\"} - sipproxyd_call_control_orig_redirection_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Redirected"
    }
   ]
  },
  {
   "title": "Call Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_call_control_orig_authentication_required_total{instance=\"$instance\"} - sipproxyd_call_control_orig_authentication_required_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Auth required"
    },
    {
     "expr": "sum(sipproxyd_call_control_orig_client_error_total{instance=\"$instance\"} - sipproxyd_call_control_orig_client_error_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Client error"
    },
    {
     "expr": "sum(sipproxyd_call_control_orig_server_error_total{instance=\"$instance\"} - sipproxyd_call_control_orig_server_error_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Server error"
    },
    {
     "expr": "sum(sipproxyd_call_control_orig_global_error_total{instance=\"$instance\"} - sipproxyd_call_control_orig_global_error_total{instance=\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Global error"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Transaction TU Manager Queue Summary",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_transaction_and_tu_tu_manager_queue_size_current{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "current"
    },
    {
     "expr": "sum(sipproxyd_transaction_and_tu_tu_manager_queue_size_lastmax{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "last max "
    },
    {
     "expr": "sum(sipproxyd_transaction_and_tu_tu_manager_queue_size_lastmin{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "last min"
    },
    {
     "expr": "sum(sipproxyd_transaction_and_tu_tu_manager_queue_size_lastavg{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "last avg"
    }
   ]
  },
  {
   "title": "Transaction TU Manager Reinject Queue Summary",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_transaction_and_tu_tu_manager_reinject_queue_current{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "current"
    },
    {
     "expr": "sum(sipproxyd_transaction_and_tu_tu_manager_reinject_queue_lastmax{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "last max "
    },
    {
     "expr": "sum(sipproxyd_transaction_and_tu_tu_manager_reinject_queue_lastmin{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "last min"
    },
    {
     "expr": "sum(sipproxyd_transaction_and_tu_tu_manager_reinject_queue_lastavg{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "last avg"
    }
   ]
  },
  {
   "title": "Notification Queue Summary",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_presence_notification_queue_size_current{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "current"
    },
    {
     "expr": "sum(sipproxyd_presence_notification_queue_size_lastmax{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "last max "
    },
    {
     "expr": "sum(sipproxyd_presence_notification_queue_size_lastmin{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "last min"
    },
    {
     "expr": "sum(sipproxyd_presence_notification_queue_size_lastavg{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "last avg"
    }
   ]
  },
  {
   "title": "Transaction TU Manager Queue Sizes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_transaction_and_tu_tu_manager_queue_size_current{instance=~\"$instance\"}) by (idx)",
     "legendFormat": "current #{{ idx }}"
    },
    {
     "expr": "sum(sipproxyd_transaction_and_tu_tu_manager_queue_size_lastmax{instance=~\"$instance\"}) by (idx)",
     "legendFormat": "last max #{{ idx }}"
    }
   ]
  },
  {
   "title": "Transaction TU Manager Reinject Queue Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_transaction_and_tu_tu_manager_reinject_queue_current{instance=~\"$instance\"}) by (idx)",
     "legendFormat": "current #{{ idx }}"
    },
    {
     "expr": "sum(sipproxyd_transaction_and_tu_tu_manager_reinject_queue_lastmax{instance=~\"$instance\"}) by (idx)",
     "legendFormat": "last max #{{ idx }}"
    }
   ]
  },
  {
   "title": "Notification Queue Sizes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_presence_notification_queue_size_current{instance=~\"$instance\"}) by (idx)",
     "legendFormat": "current #{{ idx }}"
    },
    {
     "expr": "sum(sipproxyd_presence_notification_queue_size_lastmax{instance=~\"$instance\"}) by (idx)",
     "legendFormat": "last max #{{ idx }}"
    }
   ]
  },
  { "title": "Transport", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Request Methods",
   "type": "graph",
   "description": "Number of requests being received or sent",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_request_method_invite_in_total{instance=~\"$instance\"} - sipproxyd_request_method_invite_in_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "INVITE IN"
    },
    {
     "expr": "sum(sipproxyd_request_method_subscribe_in_total{instance=~\"$instance\"} - sipproxyd_request_method_subscribe_in_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "SUBSCRIBE IN"
    },
    {
     "expr": "sum(sipproxyd_request_method_notify_out_total{instance=~\"$instance\"} - sipproxyd_request_method_notify_out_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "NOTIFY OUT"
    },
    {
     "expr": "sum(registrard_request_method_register_in_total{instance=~\"$instance\"} - registrard_request_method_register_in_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "REGISTER IN"
    }
   ]
  },
  {
   "title": "Transport Messages",
   "type": "graph",
   "description": "Number of messages received or sent",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_transport_message_in_total{instance=~\"$instance\"} - sipproxyd_transport_message_in_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "RETRY IN"
    },
    {
     "expr": "sum(sipproxyd_transport_message_out_total{instance=~\"$instance\"} - sipproxyd_transport_message_out_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "RETRY OUT"
    }
   ]
  },
  {
   "title": "Transaction Retries",
   "type": "graph",
   "description": "Number of messages retried for transaction and transaction user layer",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_transaction_and_tu_retry_in_total{instance=~\"$instance\"} - sipproxyd_transaction_and_tu_retry_in_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "RETRY IN"
    },
    {
     "expr": "sum(sipproxyd_transaction_and_tu_retry_out_total{instance=~\"$instance\"} - sipproxyd_transaction_and_tu_retry_out_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "RETRY OUT"
    }
   ]
  },
  { "title": "Internal Communication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "WebSocket Connections",
   "type": "graph",
   "description": "Number of active websocket connections",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sipproxyd_ws_connections_current{instance=~\"$instance\"} ",
     "legendFormat": "active"
    },
    {
     "expr": "sipproxyd_ws_connections_lastmin{instance=~\"$instance\"} ",
     "legendFormat": "last min"
    },
    {
     "expr": "sipproxyd_ws_connections_lastmax{instance=~\"$instance\"} ",
     "legendFormat": "last max"
    }
   ]
  },
  {
   "title": "RCC Connections",
   "type": "graph",
   "description": "Number of active websocket connections",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sipproxyd_general_rcc_active_connections_current{instance=~\"$instance\"}",
     "legendFormat": "active"
    },
    {
     "expr": "sipproxyd_general_rcc_active_connections_lastmin{instance=~\"$instance\"} ",
     "legendFormat": "last min"
    },
    {
     "expr": "sipproxyd_general_rcc_active_connections_lastmax{instance=~\"$instance\"} ",
     "legendFormat": "last max"
    }
   ]
  },
  {
   "title": "WebSocket Messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_ws_agent_ev_in_total{instance=~\"$instance\"} - sipproxyd_ws_agent_ev_in_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Agent in"
    },
    {
     "expr": "sum(sipproxyd_ws_agent_ev_out_total{instance=~\"$instance\"} - sipproxyd_ws_agent_ev_out_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Agent out"
    },
    {
     "expr": "sum(sipproxyd_ws_call_ev_total{instance=~\"$instance\"} - sipproxyd_ws_call_ev_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Calls"
    },
    {
     "expr": "sum(sipproxyd_ws_call_notify_in_total{instance=~\"$instance\"} - sipproxyd_ws_call_notify_in_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Call notify in"
    },
    {
     "expr": "sum(sipproxyd_ws_call_notify_out_total{instance=~\"$instance\"} - sipproxyd_ws_call_notify_out_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Call notify out"
    },
    {
     "expr": "sum(sipproxyd_ws_call_sync_in_total{instance=~\"$instance\"} - sipproxyd_ws_call_sync_in_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Call sync in"
    },
    {
     "expr": "sum(sipproxyd_ws_call_sync_out_total{instance=~\"$instance\"} - sipproxyd_ws_call_sync_out_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Call sync out"
    }
   ]
  },
  {
   "title": "RCC Messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sipproxyd_general_rcc_in_commands_total{instance=~\"$instance\"} - sipproxyd_general_rcc_in_commands_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Commands in"
    },
    {
     "expr": "sum(sipproxyd_general_rcc_out_commands_total{instance=~\"$instance\"} - sipproxyd_general_rcc_out_commands_total{instance=~\"$instance\"} offset $__interval >= 0) by (instance)",
     "legendFormat": "Commands out"
    }
   ]
  },
  {
   "title": "C5 Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(process_cpu_seconds_system_total{instance=~\"$instance\",job=\"c5-exporter\"} - process_cpu_seconds_system_total{instance=~\"$instance\",job=\"c5-exporter\"} offset $__interval >= 0) by (detector)",
       "legendFormat": "system"
      },
      {
       "expr": "sum(process_cpu_seconds_user_total{instance=~\"$instance\",job=\"c5-exporter\"} - process_cpu_seconds_user_total{instance=~\"$instance\",job=\"c5-exporter\"} offset $__interval >= 0) by (detector)",
       "legendFormat": "user"
      }
     ]
    },
    {
     "title": "Go Process Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
       "legendFormat": "Resident"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{instance=~\"$instance\"}",
       "legendFormat": "Heap used"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance\"}",
       "legendFormat": "Stack used"
      }
     ]
    },
    {
     "title": "Go Internals",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{instance=~\"$instance\"}",
       "legendFormat": "Open files"
      },
      {
       "expr": "go_goroutines{instance=~\"$instance\"}",
       "legendFormat": "Go Routines"
      },
      {
       "expr": "go_threads{instance=~\"$instance\"}",
       "legendFormat": "Go Threads"
      }
     ]
    }
   ]
  }
 ]
}